run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - asciicheck
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - makezero
    - nilerr
    - nolintlint
    - predeclared
    - promlinter
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/f-pisani/gmail-cli-tools
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    excludes:
      - G304 # File path provided as CLI argument
      - G204 # Audit use of command execution

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec